#pragma once

#define LITTLEFS_MOUNT_POINT "/lfs"
#define LITTLEFS_HTTP_ROOT LITTLEFS_MOUNT_POINT "/www"
#define LITTLEFS_HTTP_PORT 8080
#define LITTLEFS_HTTP_INDEX LITTLEFS_HTTP_ROOT "/index.html"

#define BME_LOG_DIR LITTLEFS_MOUNT_POINT "/logs"
#define BME_LOG_PATH_DEFAULT BME_LOG_DIR "/bme.log"
#define BME_LOG_PATH_MAX 128
#define LTR_LOG_DIR BME_LOG_DIR
#define LTR_LOG_PATH_DEFAULT LTR_LOG_DIR "/ltr.log"
#define LTR_LOG_PATH_MAX BME_LOG_PATH_MAX
#define MAX17048_LOG_DIR BME_LOG_DIR
#define MAX17048_LOG_PATH_DEFAULT MAX17048_LOG_DIR "/max17048.log"
#define MAX17048_LOG_PATH_MAX BME_LOG_PATH_MAX
#define LSM6DSL_LOG_DIR BME_LOG_DIR
#define LSM6DSL_LOG_PATH_DEFAULT LSM6DSL_LOG_DIR "/lsm6dsl.log"
#define LSM6DSL_LOG_PATH_MAX BME_LOG_PATH_MAX
