
# Console / printk
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_PRINTK=y

# Logging (optional, but useful)
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Heap (Wi-Fi needs more headroom)
CONFIG_HEAP_MEM_POOL_SIZE=98304

# Hardware info (reset cause)
CONFIG_HWINFO=y

# Shell over UART
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_BACKEND_SERIAL_API_POLLING=y
CONFIG_SHELL_BACKEND_SERIAL_INTERRUPT_DRIVEN=n
CONFIG_SHELL_AUTOSTART=y
CONFIG_SHELL_PROMPT_UART="sparrow$ "
CONFIG_SHELL_STACK_SIZE=5200
CONFIG_SHELL_CMD_BUFF_SIZE=256
CONFIG_SHELL_HISTORY=y
CONFIG_SHELL_HISTORY_BUFFER=512

# I2C
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_I2S=y

# LED strip (NeoPixel)
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_I2S=y

# Display (SSD1306 OLED)
CONFIG_DISPLAY=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_CHARACTER_FRAMEBUFFER_USE_DEFAULT_FONTS=y
CONFIG_SSD1306=y

# Sensors
CONFIG_SENSOR=y
CONFIG_BME680=y
CONFIG_LSM6DSL=y
CONFIG_LSM6DSL_ENABLE_TEMP=y
CONFIG_LSM6DSL_ACCEL_FS=0
CONFIG_LSM6DSL_ACCEL_ODR=0
CONFIG_LSM6DSL_GYRO_FS=0
CONFIG_LSM6DSL_GYRO_ODR=0
CONFIG_FUEL_GAUGE=y
CONFIG_MAX17048=y

# File system (LittleFS on internal flash)
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_SHELL=y

# Networking / Wi-Fi shell
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_DHCPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NET_SHELL=y
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y
CONFIG_NET_L2_WIFI_SHELL=y
CONFIG_NET_MGMT_EVENT_QUEUE_TIMEOUT=5000
CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=16
CONFIG_NET_SOCKETS=y
CONFIG_DNS_RESOLVER=y
CONFIG_DNS_RESOLVER_AUTO_INIT=y
CONFIG_DNS_SERVER_IP_ADDRESSES=y
CONFIG_DNS_SERVER1="8.8.8.8"
CONFIG_NET_DHCPV4_OPTION_DNS_ADDRESS=y
CONFIG_NET_DHCPV4_DNS_SERVER_VIA_INTERFACE=y
CONFIG_SNTP=y

# HTTP file server (LittleFS)
CONFIG_HTTP_SERVER=y
# HTTP server uses its own eventfd and polls multiple sockets.
CONFIG_ZVFS_EVENTFD_MAX=2
CONFIG_ZVFS_POLL_MAX=10
